name: grc
version: '1.0.0'
main: farahsoftware.co.za.grc
api-version: '1.13'
authors: [ GuardianTheOG ]
description: Right-Click Plugin
website: farahsoftware.co.za

commands:
  grc:
    description: Main command for the GRC plugin
    usage: /<command>
    permission: grc.admin
    permission-message: "&cYou don't have permission to use GRC commands"

permissions:
  grc.admin:
      default: op
